const question = [
    "./img/공공.png",
    "./img/공서방.png",
    "./img/구영감.png",
    "./img/구옹.png",
    "./img/그윈.png",
    "./img/나란.png",
    "./img/나미녀.png",
    "./img/나탈리.png",
    "./img/넬라.png",
    "./img/노공.png",
    "./img/노마.png",
    "./img/누리스.png",
    "./img/다크로드.png",
    "./img/달숙.png",
    "./img/덴마.png",
    "./img/도공.png",
    "./img/도의진.png",
    "./img/돈 지오바네.png",
    "./img/돌팔이.png",
    "./img/돼지와 함께 춤을.png",
    "./img/뒷골목의 제이엠.png",
    "./img/떠돌이 연금술사.png",
    "./img/라야.png",
    "./img/라엘.png",
    "./img/라케리스.png",
    "./img/란밍.png",
    "./img/로엘.png",
    "./img/루오 할아범.png",
    "./img/루퍼트.png",
    "./img/루피.png",
    "./img/리니.png",
    "./img/리리슈슈.png",
    "./img/리엘.png",
    "./img/마야.png",
    "./img/마이.png",
    "./img/마파.png",
    "./img/만슈타인.png",
    "./img/만지.png",
    "./img/멜.png",
    "./img/몽땅따.png",
    "./img/몽롱 할배.png",
    "./img/몽롱.png",
    "./img/무탄.png",
    "./img/뮤.png",
    "./img/미르겔.png",
    "./img/밍밍부인.png",
    "./img/바른.png",
    "./img/바리.png",
    "./img/베티.png",
    "./img/브루스.png",
    "./img/브리트니.png",
    "./img/비디원.png",
    "./img/비셔스.png",
    "./img/빅스.png",
    "./img/빌리.png",
    "./img/사비트라마.png",
    "./img/샨.png",
    "./img/샹크스.png",
    "./img/서나.png",
    "./img/선더.png",
    "./img/소원기.png",
    "./img/소피아.png",
    "./img/슈미.png",
    "./img/슈앵.png",
    "./img/슈피겔만.png",
    "./img/스미스.png",
    "./img/스크루지.png",
    "./img/슬린.png",
    "./img/시드.png",
    "./img/시라스.png",
    "./img/시종 이크.png",
    "./img/아르미.png",
    "./img/아세손.png",
    "./img/안드레아.png",
    "./img/알렉스.png",
    "./img/에린.png",
    "./img/엘모스.png",
    "./img/여신 미네르바.png",
    "./img/요정 로웬.png",
    "./img/요정 마르.png",
    "./img/요정 아르웬.png",
    "./img/요정 에뜨랑.png",
    "./img/요정 윙.png",
    "./img/우양.png",
    "./img/웅이.png",
    "./img/윈스턴.png",
    "./img/유타.png",
    "./img/이그네트 .png",
    "./img/이스.png",
    "./img/이얀.png",
    "./img/이카루스.png",
    "./img/이프.png",
    "./img/장로 스탄.png",
    "./img/정체불명의 그녀.png",
    "./img/제라스.png",
    "./img/제이.png",
    "./img/존.png",
    "./img/주먹펴고 일어서.png",
    "./img/지니.png",
    "./img/천지.png",
    "./img/카밀라.png",
    "./img/카이지.png",
    "./img/쿤.png",
    "./img/큐트.png",
    "./img/크리슈라마.png",
    "./img/클로이.png",
    "./img/클로토.png",
    "./img/클리프.png",
    "./img/타미.png",
    "./img/태상.png",
    "./img/테오.png",
    "./img/토리.png",
    "./img/토미.png",
    "./img/툴카스.png",
    "./img/티앤크.png",
    "./img/티티앙.png",
    "./img/파타.png",
    "./img/판서방.png",
    "./img/페이슨.png",
    "./img/페티트.png",
    "./img/펠라스.png",
    "./img/푸린.png",
    "./img/프레드릭.png",
    "./img/피아.png",
    "./img/하인즈.png",
    "./img/학.png",
    "./img/한태수.png",
    "./img/헬레나.png",
    "./img/황선장.png",
]


export default question;